### PR TITLE
Add an option to use current rom directory for config and saves

### LINKED ISSUE #78: [Feature Request] Add option to use rom folder for save files
I have configured my emulators to write save files in the same folders as the rom files to be able to quickly copy roms + saves to another system. Therefor it would be nice to have the option in OAF too.
Due to other emulators writing the wrong EEPROM format it might be useful to only enable overriding same-folder save files if they could be read correctly to avoid overriding existing saves with fresh ones.

### PR DESCRIPTION
**Pull request by Exagone313**
Closes #78

### CODE REVIEW

**Comment by Exagone313** [comment]
I forgot to document it, will do later.

**Comment by Exagone313** [comment]
Yes, my bad, will do right now.

**Comment by profi200** [comment]
The if() is still there. Maybe something went wrong with your force push.

**Comment by Exagone313** [comment]
What `if`? I don't think you have sent your review.

**Comment by profi200** [comment]
This one. The comment placement in the review is a bit misleading. Sorry.

https://github.com/profi200/open_agb_firm/pull/209/files#diff-4179aa8356d7d1351376d5439df2547aa0f4738f2815ab295efc9c4e422756c4R261

**Comment by Exagone313** [comment]
If you click on `Start review` (the green button), your comment is set as `Pending` and is only for you to see, you need to click on `Finish your review` on the top of the page to send it.
Or, you can click on `Add single comment` to send it directly.

I'm going to remove that change.

**Comment by profi200** [comment]
Yeah, this is on me. Sorry.

**Pull request merged**
